# Generated by Django 2.2.18 on 2023-11-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20231105_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
