# Generated by Django 2.2.18 on 2023-11-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20231105_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogintimestamp',
            old_name='login_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userlogintimestamp',
            name='logout_timestamp',
        ),
    ]
