# Generated by Django 2.2.18 on 2023-11-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
