# Generated by Django 2.2.18 on 2023-10-27 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fluido', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_fluido', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_experimento', models.CharField(max_length=200)),
                ('corriente', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('frecuencia', models.FloatField(null=True)),
                ('tiempo', models.TimeField(null=True)),
                ('sensibilidad', models.FloatField(null=True)),
                ('pasos', models.FloatField(null=True)),
                ('fecha_experimento', models.DateField(auto_now_add=True)),
                ('pdf_experimento', models.FileField(blank=True, null=True, upload_to='experimento_pdf/')),
                ('tiempo_pausa', models.DurationField(default=datetime.timedelta(0))),
                ('fluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.Fluido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
