# Generated by Django 3.2.2 on 2023-09-12 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fluido', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_fluido', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_experimento', models.CharField(max_length=200)),
                ('electricidad', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('tiempo', models.TimeField(null=True)),
                ('fecha_experimento', models.DateField(auto_now_add=True)),
                ('pdf_experimento', models.FileField(blank=True, null=True, upload_to='experimento_pdf/')),
                ('fluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.fluido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
