# Generated by Django 3.2.20 on 2023-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0002_auto_20231028_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentos',
            name='corriente',
        ),
        migrations.AddField(
            model_name='experimentos',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
