# Generated by Django 3.2.20 on 2023-10-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0003_auto_20231028_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentos',
            name='final_frecuency',
            field=models.FloatField(null=True),
        ),
    ]
