# Generated by Django 3.2.20 on 2023-10-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0004_experimentos_final_frecuency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentos',
            old_name='frecuencia',
            new_name='frecuencia_inicial',
        ),
    ]
