# Generated by Django 3.2.20 on 2023-09-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0004_auto_20230917_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
