# Generated by Django 3.2.20 on 2023-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0005_rename_frecuencia_experimentos_frecuencia_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentos',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
