# Generated by Django 3.2.2 on 2023-10-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0008_auto_20231015_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
