# Generated by Django 3.2.20 on 2023-10-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0009_auto_20231015_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentos',
            old_name='electricidad',
            new_name='corriente',
        ),
        migrations.AddField(
            model_name='experimentos',
            name='frecuencia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='experimentos',
            name='pasos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='experimentos',
            name='resistencia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='experimentos',
            name='sensibilidad',
            field=models.FloatField(null=True),
        ),
    ]
