# Generated by Django 3.2.20 on 2023-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0012_auto_20231020_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentos',
            old_name='frecuencia',
            new_name='frecuencia_final',
        ),
        migrations.AddField(
            model_name='experimentos',
            name='frecuencia_inicial',
            field=models.FloatField(null=True),
        ),
    ]
